import { useState, useEffect } from 'react';
import Head from 'next/head';

import styles from './PageContainer.module.css';

export default function PageContainer({ children }) {

    return (
        <>
            <Head>
                <title>Ben Aw Yong</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.page_container}>
                <div className={styles.middle}>
                    {children}
                </div>
            </div>
        </>
    )
}